ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of GldGrv_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_36 = ', GC_36
      WRITE(*,2) 'GC_615 = ', GC_615
      WRITE(*,2) 'GC_644 = ', GC_644
      WRITE(*,2) 'GC_772 = ', GC_772
